# Generated by Django 4.1.4 on 2023-03-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='Image_1080',
            field=models.ImageField(blank=True, null=True, upload_to='images1080/'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='Image_720',
            field=models.ImageField(blank=True, null=True, upload_to='images720/'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='Image',
            field=models.ImageField(upload_to='images2k/'),
        ),
    ]
