# Generated by Django 4.1.4 on 2023-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0002_wallpaper_image_1080_wallpaper_image_720_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='Size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
