# Generated by Django 4.1.4 on 2023-03-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0004_rename_size_wallpaper_dimentions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallpaper',
            options={'ordering': ['-created_at']},
        ),
    ]
