# Generated by Django 4.1.4 on 2023-03-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0005_alter_wallpaper_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallpaper',
            options={},
        ),
    ]
