# Generated by Django 4.1.4 on 2023-03-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0006_alter_wallpaper_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallpaper',
            options={'ordering': ['-created_at']},
        ),
    ]
