# Generated by Django 4.1.4 on 2023-03-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0009_alter_wallpaper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='combined_field',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
